version: "3"
services:
  directus:
    image: directus/directus:10.7.1
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: 1
      EXTENSIONS_AUTO_RELOAD: 1
      POLYGON_API_KEY: '7q0Th2Wpj_JJJnExrV6CpYp4jpsfnLDW'
      PAYSTACK_SECRET_KEY: 'sk_test_8c42453a42a1009f2398b3c327526f0b3138094d'
      PAYSTACK_INTEGRATION_CURRENCY: 'NGN'
